### ISSUE TITLE
Posibil bug in customizer

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/pixova-lite#11]
<img width="1117" alt="screen shot 2016-03-23 at 21 55 11" src="https://cloud.githubusercontent.com/assets/7841556/13998834/f0a5c94e-f141-11e5-9e05-4e6213a5ba39.png">

Se poate vedea mai bine in Customizer-ul din STG2. Problema e ca acel background si efect de parallax n-ar trebui sa apara pe alta sectiune in afara de header.

**Comment by ioanrobciuc** [comment]
@cristianraiber, am rezolvat această problemă în acest commit: 6bab0d6.
