### ISSUE TITLE
Slider testimoniale: layout stricat

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/pixova-lite#13]
Cand ai implementat caruselul pt. recent posts, ai stricat layout-ul celui de la testimoniale. Vezi **screenshot cu ce era inainte** si compara cu ce e acum. 

![old-layout](https://cloud.githubusercontent.com/assets/7841556/14017944/8ef222f0-f1d3-11e5-96c2-01eb2ab7e4a0.png)

**Comment by ioanrobciuc** [comment]
@cristianraiber, acest issue a fost rezolvată în acest commit: bb2af20.
