### ISSUE TITLE
Changing the widgets in the customizer does not work

### ISSUE THREAD

**Issue by IonRutz** [ColorlibHQ/pixova-lite#21]
It gives an error, check screenshot.

![customize-widgets](https://cloud.githubusercontent.com/assets/15014267/14244742/69a595e6-fa65-11e5-9355-8c160b24006f.png)

Daca tot suntem aici, poate poti sa schimbi culoarea de la text widget in alb, acum e ceva pe gri si nu se vede scrisul.

Thx

**Comment by cristianraiber** [comment]
Poate aducem si selective refresh pt. widgetzi (https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/). Would be nice to have.
