### ISSUE TITLE
Integrare cu WooCommerce

### ISSUE THREAD

**Issue by ioanrobciuc** [ColorlibHQ/pixova-lite#4]
Integrare cu WooCommerce.

**Comment by cristianraiber** [comment]
Tab-ul WooCommerce ar trebui sa fie principal, nu ascuns sub Theme Options ca sub-tab.

**Comment by cristianraiber** [comment]
Inca o mica modificare aici, vezi screenshot-ul meu. Pozitionarea meniului Woo si culoarea. Make it sexy :dancer: 

![image](https://cloud.githubusercontent.com/assets/7841556/14017866/ff5a7dcc-f1d2-11e5-90d6-7c6270e3b553.png)
