### ISSUE TITLE
Team section needs some padding-bottom

### ISSUE THREAD

**Issue by IonRutz** [ColorlibHQ/pixova-lite#40]
Team social links overlapped by contact section.
Thx

**Comment by cristianraiber** [comment]
@IonRutz - un screenshot ar ajuta f. mult

**Comment by IonRutz** [comment]
![team](https://cloud.githubusercontent.com/assets/15014267/16732275/0c8025f8-4785-11e6-8630-7d08a74a5644.jpg)
