### ISSUE TITLE
Call to action header scroll bug

### ISSUE THREAD

**Issue by gonzalezkendrick97** [ColorlibHQ/pixova-lite#41]
when you scroll fast the cta header seems to be changing the height... you can easily see it when you delete all the content rows

**Comment by cristianraiber** [comment]
@cabilliant - any details as to which browser, OS and resolution you're using?

**Comment by gonzalezkendrick97** [comment]
I tested it on chrome and firefox (latest versions) windows 10 and 1440x990

**Comment by cristianraiber** [comment]
@cabilliant - Cool, thanks for letting us know :) We'll look into it.

**Comment by gonzalezkendrick97** [comment]
thank you!

**Comment by gonzalezkendrick97** [comment]
and I noticed that the horizontal rule "intro-cta-title::after" on the cta, is still visible even when the content fills and buttons are empty... or is it pro exclusive option?

**Comment by cristianraiber** [comment]
Shouldn't be. Thanks for reporting it. We'll look into this one as well.

**Comment by cristianraiber** [comment]
@giucu91 - How can I test this?

**Comment by giucu91** [comment]
I tested like @gonzalezkendrick97 said in his ticket. I removed all the sections and after that I just scrolled fast and everything was ok. This is the reason why there is not a commit on this issue.
