### ISSUE TITLE
IE homepage picture malfunction

### ISSUE THREAD

**Issue by IonRutz** [ColorlibHQ/pixova-lite#42]
After clearing the browser's history, the page loads fine. Hitting refresh shows the issue.
![ie-pixova](https://cloud.githubusercontent.com/assets/15014267/17370364/72e8d5ac-59a4-11e6-8772-5768279fd1ea.gif)

**Comment by cristianraiber** [comment]
@IonRutz - o versiune de IE si Operating System?

**Comment by IonRutz** [comment]
@cristianraiber astept raspuns de la client si revin cu informatii

la mine arata si mai rau, nu ii ia scripts.js
in compatibility mode, unde mi-a dat o eroare ca nu pare sa functioneaze:
![image](https://cloud.githubusercontent.com/assets/15014267/17382666/a71ee43e-59da-11e6-81a3-af72cfa34c16.png)

fara compatibility:
![image](https://cloud.githubusercontent.com/assets/15014267/17382720/05bdaa16-59db-11e6-8ba9-1ef05a200fb9.png)

**Comment by cristianraiber** [comment]
We don't care for IE mai jos de 11 (parca asta-i latest version pe Windows 10)

**Comment by IonRutz** [comment]
asta e versiunea de IE de la primul filmulet (sistemul clientului)
![image001](https://cloud.githubusercontent.com/assets/15014267/17436507/21142330-5b20-11e6-9065-c8a50950a42c.png)
![image002](https://cloud.githubusercontent.com/assets/15014267/17436508/222c3dac-5b20-11e6-9fb6-56bfcf6bd1cf.png)

**Comment by cristianraiber** [comment]
Possible fix: use `background-attachment: fixed;` instead of `parallax.js`

**Comment by giucu91** [comment]
@c0sm1n87 This issue is for IE8 & 11, do we support this browser?

**Comment by cristianraiber** [comment]
We only support Edge.
