### ISSUE TITLE
Top header spacing

### ISSUE THREAD

**Issue by IonRutz** [ColorlibHQ/pixova-lite#43]
Titlul ascuns in spatele header-ului

---

![image](https://cloud.githubusercontent.com/assets/15014267/17715058/3113f852-640b-11e6-979c-98642213f74e.png)

**Comment by ngabyn** [comment]
Some usecase here ? 
Can't reproduce this...

**Comment by IonRutz** [comment]
cand am testat eu se intampla in momentul in care se folosea un logo mai mare decat default-ul. din cate stiu se lua marimea logo-ului folosit fara niciun resize, iar cand e mai mare logo-ul atunci se duce header-ul peste titlu. mai verific maine daca nu reusesti sa reproduci

**Comment by giucu91** [comment]
@ngabyn @cristianraiber If we put a bigger logo the header increases in height and then the header will be over the CTA section ( the header has fixed position ). How should we proceed here?
