### ISSUE TITLE
Change contact section address & customer support

### ISSUE THREAD

**Issue by IonRutz** [ColorlibHQ/pixova-lite#48]
![image](https://cloud.githubusercontent.com/assets/15014267/18390084/7fcfef74-76b1-11e6-840c-57f602de1e5d.png)

**Comment by giucu91** [comment]
@ngabyn @cristianraiber What should I do here ? I'm not sure I understand.

**Comment by cristianraiber** [comment]
@giucu91 - What did you do here ?

**Comment by giucu91** [comment]
@cristianraiber I added two new controls in order to change "Address" and "Customer Support"
