### ISSUE TITLE
Woocommerce Star Rating Misplaced

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/pixova-lite#50]
Hello, 

I've downloaded the woocommerce plugin for my shop. Everything is fine but I was wondering if the problem comes from woocommerce or the Pixova Lite theme. 
When a buyer wants to leave a rating they can't select the stars. And I've noticed that one star was on the top left corner of the product image. I've uploaded two screenshots of my website with the source code. 

Site URL: http://robomotic.org

**Comment by Lawris** [comment]
![no stars](https://cloud.githubusercontent.com/assets/15719068/20297917/57479dea-ab13-11e6-98fa-4c6d0a4d6047.png)
![star misplaced](https://cloud.githubusercontent.com/assets/15719068/20297925/5ac71090-ab13-11e6-9de4-3718ba14410e.png)

The screenshots

**Comment by cristianraiber** [comment]
@Lawris - thank you so much for this!
