### ISSUE TITLE
Introduce color schemes 

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/pixova-lite#71]
* we'll be using the same ones as in newsmag lite

**Comment by cristianraiber** [comment]
See this: (Illdy theme)

![image](https://user-images.githubusercontent.com/7841556/28871837-fcc03884-778e-11e7-8e69-e62195c59123.png)

**Comment by cristianraiber** [comment]
It doesn't look like the color schemes are being applied everywhere. For example, the accent color didn't change everywhere

---


![image](https://user-images.githubusercontent.com/7841556/28872226-f330eca8-7790-11e7-95b0-c4631e6a7674.png)

**Comment by giucu91** [comment]
@cristianraiber the pie charts' colors will not be changed by the color schemes because it will mess up the clients colors if we remove controls for each pie chart in order to overwrite them with the accent color.
